-- Script completo para crear tabla USUARIOS en Oracle Cloud Database
-- Ejecutar este script ANTES de iniciar la aplicación Spring Boot

-- 1. Crear la secuencia para los IDs
CREATE SEQUENCE USUARIO_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 2. Crear la tabla USUARIOS
CREATE TABLE USUARIOS (
    ID NUMBER(19) PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(150) NOT NULL UNIQUE,
    TELEFONO VARCHAR2(20),
    ROL VARCHAR2(50),
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTIVO NUMBER(1) DEFAULT 1 CHECK (ACTIVO IN (0,1))
);

-- 3. Crear índices para mejorar rendimiento
CREATE INDEX IDX_USUARIOS_EMAIL ON USUARIOS(EMAIL);
CREATE INDEX IDX_USUARIOS_ROL ON USUARIOS(ROL);
CREATE INDEX IDX_USUARIOS_ACTIVO ON USUARIOS(ACTIVO);

-- 4. Insertar datos de prueba
INSERT INTO USUARIOS (ID, NOMBRE, EMAIL, TELEFONO, ROL, FECHA_REGISTRO, ACTIVO) 
VALUES (USUARIO_SEQ.NEXTVAL, 'Juan Pérez', 'juan.perez@email.com', '987654321', 'ADMIN', CURRENT_TIMESTAMP, 1);

INSERT INTO USUARIOS (ID, NOMBRE, EMAIL, TELEFONO, ROL, FECHA_REGISTRO, ACTIVO) 
VALUES (USUARIO_SEQ.NEXTVAL, 'María González', 'maria.gonzalez@email.com', '987654322', 'CLIENTE', CURRENT_TIMESTAMP, 1);

INSERT INTO USUARIOS (ID, NOMBRE, EMAIL, TELEFONO, ROL, FECHA_REGISTRO, ACTIVO) 
VALUES (USUARIO_SEQ.NEXTVAL, 'Carlos Rodríguez', 'carlos.rodriguez@email.com', '987654323', 'VENDEDOR', CURRENT_TIMESTAMP, 1);

INSERT INTO USUARIOS (ID, NOMBRE, EMAIL, TELEFONO, ROL, FECHA_REGISTRO, ACTIVO) 
VALUES (USUARIO_SEQ.NEXTVAL, 'Ana López', 'ana.lopez@email.com', '987654324', 'CLIENTE', CURRENT_TIMESTAMP, 1);

INSERT INTO USUARIOS (ID, NOMBRE, EMAIL, TELEFONO, ROL, FECHA_REGISTRO, ACTIVO) 
VALUES (USUARIO_SEQ.NEXTVAL, 'Pedro Martínez', 'pedro.martinez@email.com', '987654325', 'CLIENTE', CURRENT_TIMESTAMP, 1);

INSERT INTO USUARIOS (ID, NOMBRE, EMAIL, TELEFONO, ROL, FECHA_REGISTRO, ACTIVO) 
VALUES (USUARIO_SEQ.NEXTVAL, 'Laura Fernández', 'laura.fernandez@email.com', '987654326', 'VENDEDOR', CURRENT_TIMESTAMP, 0);

-- 6 usuarios activos y 1 inactivo para probar filtros

-- 5. Confirmar los cambios
COMMIT;

-- 6. Verificar que se crearon correctamente
SELECT 'Tabla creada correctamente. Total usuarios: ' || COUNT(*) AS RESULTADO 
FROM USUARIOS;

SELECT * FROM USUARIOS ORDER BY ID;
