-- Datos de prueba para Oracle Cloud Database
-- Este archivo se ejecuta automáticamente al iniciar la aplicación

INSERT INTO USUARIOS (ID, NOMBRE, EMAIL, TELEFONO, ROL, FECHA_REGISTRO, ACTIVO) 
VALUES (USUARIO_SEQ.NEXTVAL, 'Juan Pérez', 'juan.perez@email.com', '987654321', 'ADMIN', CURRENT_TIMESTAMP, 1);

INSERT INTO USUARIOS (ID, NOMBRE, EMAIL, TELEFONO, ROL, FECHA_REGISTRO, ACTIVO) 
VALUES (USUARIO_SEQ.NEXTVAL, 'María González', 'maria.gonzalez@email.com', '987654322', 'CLIENTE', CURRENT_TIMESTAMP, 1);

INSERT INTO USUARIOS (ID, NOMBRE, EMAIL, TELEFONO, ROL, FECHA_REGISTRO, ACTIVO) 
VALUES (USUARIO_SEQ.NEXTVAL, 'Carlos Rodríguez', 'carlos.rodriguez@email.com', '987654323', 'VENDEDOR', CURRENT_TIMESTAMP, 1);

INSERT INTO USUARIOS (ID, NOMBRE, EMAIL, TELEFONO, ROL, FECHA_REGISTRO, ACTIVO) 
VALUES (USUARIO_SEQ.NEXTVAL, 'Ana López', 'ana.lopez@email.com', '987654324', 'CLIENTE', CURRENT_TIMESTAMP, 1);

INSERT INTO USUARIOS (ID, NOMBRE, EMAIL, TELEFONO, ROL, FECHA_REGISTRO, ACTIVO) 
VALUES (USUARIO_SEQ.NEXTVAL, 'Pedro Martínez', 'pedro.martinez@email.com', '987654325', 'CLIENTE', CURRENT_TIMESTAMP, 1);

INSERT INTO USUARIOS (ID, NOMBRE, EMAIL, TELEFONO, ROL, FECHA_REGISTRO, ACTIVO) 
VALUES (USUARIO_SEQ.NEXTVAL, 'Laura Fernández', 'laura.fernandez@email.com', '987654326', 'VENDEDOR', CURRENT_TIMESTAMP, 0);
